version: "3"
services:
  node-app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    depends_on:
      - mongo
      - redis-cache
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adouni
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    ports:
      - 27017:27017

    volumes:
      - mongo-db-v:/data/db
  redis-cache:
    image: redis
    ports:
      - 6379:6379
    command: redis-server


volumes:
  mongo-db-v: