version: "3"
services:
  node-app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adouni
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    ports:
      - 27017:27017

    volumes:
      - mongo-db-v:/data/db


volumes:
  mongo-db-v: