version: "3"
services:
  node-app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
      #- MONGO_INITDB_DATABASE=admin

    ports:
      - 27017:27017

    volumes:
      - mongo-db-v:/data/db


volumes:
  mongo-db-v: