version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node-app:
    build: .
    # ports:
    #  - 3000-3002:3000
    environment:
      - PORT=3000
    depends_on:
      - mongo
      - redis-cache
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adouni
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db-v:/data/db
  redis-cache:
    image: redis
    command: redis-server


volumes:
  mongo-db-v: